# Generated by Django 4.2.1 on 2023-08-07 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_userwishlist_wishlistproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='ProductReview',
        ),
    ]
