# Generated by Django 4.2.2 on 2023-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
